/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilesIndexRouteImport } from './routes/files/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as FilesFileIdRouteImport } from './routes/files/$fileId'
import { Route as AdminRulesRouteImport } from './routes/admin/rules'
import { Route as AdminIntegrationsRouteImport } from './routes/admin/integrations'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesFileIdRoute = FilesFileIdRouteImport.update({
  id: '/files/$fileId',
  path: '/files/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRulesRoute = AdminRulesRouteImport.update({
  id: '/admin/rules',
  path: '/admin/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/sign-up': typeof SignUpRoute
  '/signin': typeof SigninRoute
  '/tenants': typeof TenantsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/files/$fileId': typeof FilesFileIdRoute
  '/admin/': typeof AdminIndexRoute
  '/files/': typeof FilesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/sign-up': typeof SignUpRoute
  '/signin': typeof SigninRoute
  '/tenants': typeof TenantsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/files/$fileId': typeof FilesFileIdRoute
  '/admin': typeof AdminIndexRoute
  '/files': typeof FilesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/sign-up': typeof SignUpRoute
  '/signin': typeof SigninRoute
  '/tenants': typeof TenantsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/files/$fileId': typeof FilesFileIdRoute
  '/admin/': typeof AdminIndexRoute
  '/files/': typeof FilesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/orders'
    | '/settings'
    | '/sign-up'
    | '/signin'
    | '/tenants'
    | '/admin/integrations'
    | '/admin/rules'
    | '/files/$fileId'
    | '/admin/'
    | '/files/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/orders'
    | '/settings'
    | '/sign-up'
    | '/signin'
    | '/tenants'
    | '/admin/integrations'
    | '/admin/rules'
    | '/files/$fileId'
    | '/admin'
    | '/files'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/orders'
    | '/settings'
    | '/sign-up'
    | '/signin'
    | '/tenants'
    | '/admin/integrations'
    | '/admin/rules'
    | '/files/$fileId'
    | '/admin/'
    | '/files/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrdersRoute: typeof OrdersRoute
  SettingsRoute: typeof SettingsRoute
  SignUpRoute: typeof SignUpRoute
  SigninRoute: typeof SigninRoute
  TenantsRoute: typeof TenantsRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminRulesRoute: typeof AdminRulesRoute
  FilesFileIdRoute: typeof FilesFileIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  FilesIndexRoute: typeof FilesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$fileId': {
      id: '/files/$fileId'
      path: '/files/$fileId'
      fullPath: '/files/$fileId'
      preLoaderRoute: typeof FilesFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/admin/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrdersRoute: OrdersRoute,
  SettingsRoute: SettingsRoute,
  SignUpRoute: SignUpRoute,
  SigninRoute: SigninRoute,
  TenantsRoute: TenantsRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminRulesRoute: AdminRulesRoute,
  FilesFileIdRoute: FilesFileIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  FilesIndexRoute: FilesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
